import PDFDocument from 'pdfkit';

export const generatePdf = async (sop) => {
    return new Promise((resolve, reject) => {
        const doc = new PDFDocument();
        const buffers = [];

        // collect chunks
        doc.on('data', chunk => buffers.push(chunk));
        doc.on('end', () => resolve(Buffer.concat(buffers)));
        doc.on('error', reject);

        // title
        doc.fontSize(24).text(sop.title, { align: 'center' });
        doc.moveDown();
        doc.fontSize(12).text(`Generated by SOP Generator`, { align: 'center' });
        doc.moveDown(2);

        // steps
        sop.structuredSteps.forEach((step) => {
            doc.fontSize(14)
               .fillColor('#4F46E5')
               .text(`Step ${step.step}: ${step.description}`);

            doc.fontSize(11)
               .fillColor('#555555')
               .text(`Role: ${step.role}`);

            if(step.warning){
                doc.fontSize(11)
                   .fillColor('#D97706')
                   .text(`⚠️ Warning: ${step.warning}`);
            }

            doc.moveDown();
        });

        // footer
        doc.moveDown(2);
        doc.fontSize(10)
           .fillColor('#aaaaaa')
           .text('Generated by SOP Generator', { align: 'center' });

        doc.end();
    });
};